enum ECheat
{
	eCheat_Invaild = -1,
	eCheat_BodySnatchers = 0,
	eCheat_IndestructableCars = 1,
	eCheat_InfiniteAmmo = 2,
	eCheat_InfiniteNitro = 3,
	eCheat_Invincibility = 4,
	eCheat_WeakCopCars = 5,
	eCheat_ZeroCost = 6,
	eCheat_GangWarfare = 7,
	eCheat_NightNight = 8,
	eCheat_ShortestDay = 9,
	eCheat_AllWeapons = 10,
	eCheat_AllVehicles = 11,
	eCheat_NUM_CHEATS = 12,
	eCheat_ExtraHealth = 13,
	eCheat_DoubleNitro = 14,
	eCheat_DoubleAmmoCapacity = 15,
	eCheat_ArmouredCars = 16,
	eCheat_FreeMods = 17,
	eCheat_NUMALLCHEATS = 18,
	eCheat_NUM_CHEATCODE_UNLOCKABLE = 8,
};